apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipaddresspools.metallb.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  group: metallb.io
  names:
    kind: IPAddressPool
    plural: ipaddresspools
    singular: ipaddresspool
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: l2advertisements.metallb.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  group: metallb.io
  names:
    kind: L2Advertisement
    plural: l2advertisements
    singular: l2advertisement
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
