# Official MetalLB manifest (native mode)
# Source: https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml

apiVersion: v1
kind: List
items:
{{ paste contents of:
https://raw.githubusercontent.com/metallb/metallb/v0.13.12/config/manifests/metallb-native.yaml
here }}