apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/prashanth-shetty-ds/k8s-app-gitops.git
    targetRevision: main
    path: apps

  destination:
    server: https://kubernetes.default.svc
    namespace: default   # IMPORTANT

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
