apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: gateway-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
      - name: nginx
        image: ghcr.io/nginxinc/nginx-gateway-fabric:latest
        args:
          - --gatewayclass=nginx
